"""
Reproducible generation of distributed sub-district points within a basin
bounding box.

Why this module exists: the WPT-D-26-00166 notebook hard-coded 33 hand-typed
lat/lon pairs in a Python dict. That's neither reproducible (no one can
re-derive *why* those 33 points) nor auditable (a reviewer can't check the
selection logic). This module instead samples points from real administrative
boundaries (India district/sub-district centroids via OpenStreetMap/GADM),
deterministically, so the point set can be regenerated byte-for-byte from
the same config and the same boundary-data version.

If boundary data is unavailable in a given environment, this module falls
back to a deterministic regular grid over the bbox (clearly logged as a
fallback, not silently substituted) — still reproducible, just less
administratively meaningful. The first real run should verify which path
was taken.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass

import numpy as np
import pandas as pd

logger = logging.getLogger("floodai.gis.points")


@dataclass(frozen=True)
class BasinPoint:
    basin_key: str
    point_id: str
    lat: float
    lon: float
    source: str  # "admin_centroid" or "regular_grid_fallback"
    name: str | None = None


def generate_grid_fallback_points(
    basin_key: str, bbox: dict[str, float], n_points_target: int, seed: int
) -> list[BasinPoint]:
    """
    Deterministic fallback: lay a regular lat/lon grid over bbox, sized so the
    grid has approximately n_points_target cells, then jitter very slightly
    using a seeded RNG to avoid all points landing exactly on IMD grid
    centers (which would bias nearest-neighbour lookups identically across
    points). Fully reproducible given (bbox, n_points_target, seed).
    """
    rng = np.random.default_rng(seed)
    lat_span = bbox["lat_max"] - bbox["lat_min"]
    lon_span = bbox["lon_max"] - bbox["lon_min"]
    aspect = lon_span / lat_span if lat_span > 0 else 1.0

    n_lat = max(1, int(round(np.sqrt(n_points_target / aspect))))
    n_lon = max(1, int(round(n_points_target / n_lat)))

    lats = np.linspace(bbox["lat_min"], bbox["lat_max"], n_lat + 2)[1:-1]
    lons = np.linspace(bbox["lon_min"], bbox["lon_max"], n_lon + 2)[1:-1]

    points: list[BasinPoint] = []
    for i, lat in enumerate(lats):
        for j, lon in enumerate(lons):
            jitter_lat, jitter_lon = rng.uniform(-0.02, 0.02, size=2)
            points.append(
                BasinPoint(
                    basin_key=basin_key,
                    point_id=f"{basin_key}_grid_{i:02d}_{j:02d}",
                    lat=round(float(lat + jitter_lat), 4),
                    lon=round(float(lon + jitter_lon), 4),
                    source="regular_grid_fallback",
                )
            )

    logger.warning(
        "Basin '%s': using REGULAR GRID FALLBACK (%d points). "
        "Administrative-centroid source was not available/configured. "
        "This is reproducible but not administratively meaningful — "
        "verify this is intended before treating results as basin-representative.",
        basin_key, len(points),
    )
    return points


def generate_admin_centroid_points(
    basin_key: str,
    bbox: dict[str, float],
    n_points_target: int,
    admin_boundaries_path: str,
    seed: int,
) -> list[BasinPoint]:
    """
    Preferred path: sample sub-district centroids from a real administrative
    boundary file (e.g. GADM level-2/3 India shapefile, or OSM-derived
    boundaries) clipped to bbox. Requires geopandas + the boundary file.

    If n available centroids exceeds n_points_target, a seeded random subset
    is drawn (deterministic given seed) rather than the first N encountered,
    to avoid a geographic ordering bias in the source file.
    """
    try:
        import geopandas as gpd
    except ImportError as e:
        raise RuntimeError(
            "geopandas is required for admin-centroid point generation. "
            "Install it, or accept the regular-grid fallback explicitly."
        ) from e

    gdf = gpd.read_file(admin_boundaries_path)
    gdf = gdf.cx[bbox["lon_min"]:bbox["lon_max"], bbox["lat_min"]:bbox["lat_max"]]
    if len(gdf) == 0:
        raise RuntimeError(
            f"No administrative units found within bbox for basin '{basin_key}'. "
            "Check admin_boundaries_path and bbox in config.yaml."
        )

    centroids = gdf.geometry.centroid
    candidates = pd.DataFrame({
        "name": gdf.get("NAME_2", gdf.get("NAME_3", pd.Series([None] * len(gdf)))),
        "lat": centroids.y,
        "lon": centroids.x,
    }).dropna(subset=["lat", "lon"]).reset_index(drop=True)

    rng = np.random.default_rng(seed)
    if len(candidates) > n_points_target:
        idx = rng.choice(len(candidates), size=n_points_target, replace=False)
        candidates = candidates.iloc[sorted(idx)].reset_index(drop=True)

    points = [
        BasinPoint(
            basin_key=basin_key,
            point_id=f"{basin_key}_admin_{i:03d}",
            lat=round(float(row.lat), 4),
            lon=round(float(row.lon), 4),
            source="admin_centroid",
            name=row.get("name"),
        )
        for i, row in candidates.iterrows()
    ]
    logger.info(
        "Basin '%s': generated %d admin-centroid points (target was %d).",
        basin_key, len(points), n_points_target,
    )
    return points


def basin_points_to_dataframe(points: list[BasinPoint]) -> pd.DataFrame:
    return pd.DataFrame([p.__dict__ for p in points])
